In [1]:
!git clone https://github.com/4GeeksAcademy/linear-algebra-in-python-and-numpy

Cloning into 'linear-algebra-in-python-and-numpy'...
remote: Enumerating objects: 249, done.
remote: Counting objects: 100% (249/249), done.
remote: Compressing objects: 100% (172/172), done.
remote: Total 249 (delta 118), reused 161 (delta 56), pack-reused 0 (from 0)
Receiving objects: 100% (249/249), 1.54 MiB | 6.81 MiB/s, done.
Resolving deltas: 100% (118/118), done.


01-vector-representation

In [2]:
import numpy as np  # Import NumPy to use it later

def create_vector(lst, mode="pure"):
    """
    Converts a list into a vector in pure Python or in NumPy.

    Parameters:
    - lst: list -> List of numbers that will form the vector.
    - mode: str -> "pure" for normal list, "numpy" for NumPy array.

    Returns:
    - A vector in the specified format.
    """
    if mode == "pure":
      return lst
    elif mode == "numpy":
      return np.array(lst)
# Test the function with the following values:
vector1 = create_vector([1, 2, 3], "pure")
vector2 = create_vector([1, 2, 3], "numpy")

print("Vector in pure Python:", vector1)
print("Vector in NumPy:", vector2)

Vector in pure Python: [1, 2, 3]
Vector in NumPy: [1 2 3]


02-matrix-representation

In [3]:
import numpy as np  # Import NumPy to use it later
import random  # To generate random values in pure Python

def create_matrix(n, m, mode="pure"):
    """
    Generates an n x m matrix with random values.

    Parameters:
    - n: int -> Number of rows.
    - m: int -> Number of columns.
    - mode: str -> "pure" for Python lists, "numpy" for NumPy arrays.

    Returns:
    - A matrix in the specified format.
    """
    if mode == "pure":
      matriz = []
      for _ in range(n):
        rows = []
        for _ in range(m):
          rows.append(random.randint(0,100))
        matriz.append(rows)
      return matriz
    elif mode == "numpy":
      return np.random.randint(0,100, size=(n,m))



# Test the function with the following values:
matrix1 = create_matrix(3, 3, "pure")
matrix2 = create_matrix(3, 3, "numpy")

print("Matrix in pure Python:", matrix1)
print("Matrix in NumPy:\n", matrix2)

Matrix in pure Python: [[80, 19, 2], [68, 78, 45], [15, 43, 92]]
Matrix in NumPy:
 [[44 21 14]
 [85 93 68]
 [31 50 38]]


03-vector-addition-and-subtraction

In [4]:
import numpy as np


# vectors
vector1 = [1, 2, 3]
vector2 = [4, 5, 6]

def sum_vectors(v1, v2, mode="pure"):
    """
    Computes the element-wise sum of two vectors.

    Parameters:
    - v1: list or np.array -> First vector.
    - v2: list or np.array -> Second vector.
    - mode: str -> "pure" for Python lists, "numpy" for NumPy arrays.

    Returns:
    - A vector with the element-wise sum.
    """
    if mode == "pure":
      if len(v1) == len(v2):
        return [v1[i]+v2[i] for i in range(len(v1))]
      else:
        raise ValueError("No tienen la misma longitud!")
    if mode == "numpy":
      return np.array(v1) + np.array(v2) if len(v1) == len(v2) else print("Error")

def subtract_vectors(v1, v2, mode="pure"):
    """
    Computes the element-wise subtraction of two vectors.

    Parameters:
    - v1: list or np.array -> First vector.
    - v2: list or np.array -> Second vector.
    - mode: str -> "pure" for Python lists, "numpy" for NumPy arrays.

    Returns:
    - A vector with the element-wise subtraction.
    """
    if mode == "pure":
      if len(v1) == len(v2):
        return [v2[i]-v1[i] for i in range(len(v1))]
      else:
        raise ValueError("No tienen la misma longitud")
    if mode == "numpy":
      return np.array(v2) - np.array(v1) if len(v1) == len(v2) else print("Error")

sum_result_pure = sum_vectors(vector1, vector2, "pure")
sum_result_numpy = sum_vectors(vector1, vector2, "numpy")

sub_result_pure = subtract_vectors(vector1, vector2, "pure")
sub_result_numpy = subtract_vectors(vector1, vector2, "numpy")

print("Sum in pure Python:", sum_result_pure)
print("Sum in NumPy:", sum_result_numpy)
print("Subtraction in pure Python:", sub_result_pure)
print("Subtraction in NumPy:", sub_result_numpy)

Sum in pure Python: [5, 7, 9]
Sum in NumPy: [5 7 9]
Subtraction in pure Python: [3, 3, 3]
Subtraction in NumPy: [3 3 3]


04-dot-product-and-matrix-product

In [5]:
import numpy as np

# vectors and matrices
vector1 = [1, 2, 3]
vector2 = [4, 5, 6]

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

def dot_product(v1, v2, mode="pure"):
    """
    Computes the dot product of two vectors.

    Parameters:
    - v1: list or np.array -> First vector.
    - v2: list or np.array -> Second vector.
    - mode: str -> "pure" for Python lists, "numpy" for NumPy arrays.

    Returns:
    - The dot product as a scalar value.
    """

    pass  # Remove this line when implemented

def matrix_product(A, B, mode="pure"):
    """
    Computes the product of two matrices.

    Parameters:
    - A: list of lists or np.array -> First matrix.
    - B: list of lists or np.array -> Second matrix.
    - mode: str -> "pure" for Python lists, "numpy" for NumPy arrays.

    Returns:
    - A matrix with the result of A * B.
    """
    pass  # Remove this line when implemented


dot_result_pure = dot_product(vector1, vector2, "pure")
dot_result_numpy = dot_product(vector1, vector2, "numpy")


matrix_result_pure = matrix_product(matrix1, matrix2, "pure")
matrix_result_numpy = matrix_product(matrix1, matrix2, "numpy")

print("Dot product in pure Python:", dot_result_pure)
print("Dot product in NumPy:", dot_result_numpy)
print("Matrix product in pure Python:", matrix_result_pure)
print("Matrix product in NumPy:", matrix_result_numpy)

Dot product in pure Python: None
Dot product in NumPy: None
Matrix product in pure Python: None
Matrix product in NumPy: None


05-matrix-transposition

In [74]:
import numpy as np

def transpose(matrix, mode="pure"):
    """
    Computes the transpose of a matrix.

    Parameters:
    - matrix: list of lists or np.array -> Matrix to transpose.
    - mode: str -> "pure" for Python lists, "numpy" for NumPy arrays.

    Returns:
    - The transposed matrix.
    """

    if mode == "pure":
        transpuesta = []
        for _ in range(len(matrix[0])):
          transpuesta.append([])
        for fila in matrix:
          for j in range(len(fila)):
            transpuesta[j].append(fila[j])

        return transpuesta
    if mode == "numpy":
      transpuesta2 = np.array(matrix)
      return transpuesta2.T

matrix = [[1, 2, 3],
          [4, 5, 6]]

print(transpose(matrix, "pure"))
print(transpose(matrix, "numpy"))



[[1, 4], [2, 5], [3, 6]]
[[1 4]
 [2 5]
 [3 6]]


06-determinants-and-inverses

In [84]:
import numpy as np

def determinant(matrix, mode="pure"):
    """
    Computes the determinant of a square matrix.

    Parameters:
    - matrix: list of lists or np.array -> Matrix to compute determinant.
    - mode: str -> "pure" for Python lists, "numpy" for NumPy arrays.

    Returns:
    - The determinant value.
    """

    if mode == "pure":
      determinante = matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
      return determinante
    if mode == "numpy":
      return np.linalg.det(matrix)


def inverse_matrix(matrix, mode="pure"):
    """
    Computes the inverse of a square matrix.

    Parameters:
    - matrix: list of lists or np.array -> Matrix to compute inverse.
    - mode: str -> "pure" for Python lists, "numpy" for NumPy arrays.

    Returns:
    - The inverse matrix or a message if it doesn't exist.
    """
    if mode == "pure":
      det = determinant(matrix,"pure")
      if det == 0:
        return "La matriz no tiene inversa"
      return [[matrix[1][1]/det, -matrix[0][1]/det],
          [-matrix[1][0]/det, matrix[0][0]/det]]
    if mode == "numpy":
      return np.linalg.inv(matrix)



matrix = [[1, 2],
          [3, 4]]

print(determinant(matrix, "pure"))
print(determinant(matrix, "numpy"))
print(inverse_matrix(matrix, "pure"))
print(inverse_matrix(matrix, "numpy"))


-2
-2.0000000000000004
[[-2.0, 1.0], [1.5, -0.5]]
[[-2.   1. ]
 [ 1.5 -0.5]]


07-solving-systems-of-linear-equations

In [99]:
import numpy as np

def solve_system(A, b, mode="numpy"):
    """
    Solves the linear system Ax = b.

    Parameters:
    - A: list of lists or np.array -> Coefficient matrix.
    - b: list or np.array -> Result vector.
    - mode: str -> "pure" for manual computation, "numpy" for np.linalg.solve().

    Returns:
    - The solution vector x.
    """
    if mode == "pure":
      det = determinant(A, "pure")
      if det == 0:
        return f"La matriz no tiene inversa"
      inv = inverse_matrix(A,"pure")
      x = [
          inv[0][0]*b[0] + inv[0][1]*b[1],
          inv[1][0]*b[0] + inv[1][1]*b[1]
      ]
      return f"Pythonic: {x}"
    if mode == "numpy":
      x = np.linalg.solve(A,b)
      return f"Numpy: {x}"

A = [[2, 3], [4, -1]]
b = [5, 1]

print(solve_system(A, b, "pure"))
print(solve_system(A, b, "numpy"))



Pythonic: [0.5714285714285714, 1.2857142857142856]
Numpy: [0.57142857 1.28571429]


08-eigenvalues-and-eigenvectors

In [107]:
import numpy as np

def compute_eigen(A, mode="numpy"):
    """
    Computes the eigenvalues and eigenvectors of a square matrix.

    Parameters:
    - A: list of lists or np.array -> Square matrix.
    - mode: str -> "pure" for manual calculation, "numpy" for np.linalg.eig().

    Returns:
    - List of eigenvalues (and eigenvectors if mode="numpy").
    """

    if mode == "pure":
      a,b = A[0]
      c,d = A[1]

      lambda1 = ((a+d)+((a+d)**2-4*(a*d-b*c))**0.5)/2
      lambda2 = ((a+d)-((a+d)**2-4*(a*d-b*c))**0.5)/2

      return f"Pythonic: {[lambda1,lambda2]}"
    if mode == "numpy":
      autovalores, autovectores = np.linalg.eig(A)
      return f"autovalores: {autovalores} autovectores: {autovectores}"


A = [
    [3, 2],
    [1, 4]
    ]
print(compute_eigen(A, "pure"))
print(compute_eigen(A, "numpy"))



Pythonic: [5.0, 2.0]
autovalores: [2. 5.] autovectores: [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]
